os: linux
dist: trusty
language: cpp

cache:
  - apt
  - ccache

matrix:
  include:
    ##########################################################################
    # Clang on OSX
    ##########################################################################

    # XCode 7.3
    - os: osx
      osx_image: xcode7.3
      env: BUILD_TYPE=Debug

    - os: osx
      osx_image: xcode7.3
      env: BUILD_TYPE=Release

    # XCode 8
    - os: osx
      osx_image: xcode8
      env: BUILD_TYPE=Debug

    - os: osx
      osx_image: xcode8
      env: BUILD_TYPE=Release

    # XCode 8.2
    - os: osx
      osx_image: xcode8.2
      env: BUILD_TYPE=Debug

    - os: osx
      osx_image: xcode8.2
      env: BUILD_TYPE=Release

    # XCode 8.3
    - env: COMPILER=clang++ BUILD_TYPE=Debug
      os: osx
      osx_image: xcode8.3
      compiler: clang

    - env: COMPILER=clang++ BUILD_TYPE=Release
      os: osx
      osx_image: xcode8.3
      compiler: clang

    # XCode 9.1
    - env: COMPILER=clang++ BUILD_TYPE=Debug
      os: osx
      osx_image: xcode9.1
      compiler: clang

    - env: COMPILER=clang++ BUILD_TYPE=Release
      os: osx
      osx_image: xcode9.1
      compiler: clang

    ##########################################################################
    # GCC on Linux
    ##########################################################################

    # GCC 4.8
    - env: COMPILER=g++-4.8 BUILD_TYPE=Debug
      addons: &gcc48
        apt:
          packages:
            - g++-4.8
          sources:
            - ubuntu-toolchain-r-test

    - env: COMPILER=g++-4.8 BUILD_TYPE=Release
      addons: *gcc48

    # GCC 4.9
    - env: COMPILER=g++-4.9 BUILD_TYPE=Debug
      addons: &gcc49
        apt:
          packages:
            - g++-4.9
          sources:
            - ubuntu-toolchain-r-test

    - env: COMPILER=g++-4.9 BUILD_TYPE=Release
      addons: *gcc49


    # GCC 5
    - env: COMPILER=g++-5 BUILD_TYPE=Debug
      addons: &gcc5
        apt:
          packages:
            - g++-5
          sources:
            - ubuntu-toolchain-r-test

    - env: COMPILER=g++-5 BUILD_TYPE=Release
      addons: *gcc5

    # GCC 6
    - env: COMPILER=g++-6 BUILD_TYPE=Debug
      addons: &gcc6
        apt:
          packages:
            - g++-6
          sources:
            - ubuntu-toolchain-r-test

    - env: COMPILER=g++-6 BUILD_TYPE=Release
      addons: *gcc6

    # GCC 7
    - env: COMPILER=g++-7 BUILD_TYPE=Debug
      addons: &gcc7
        apt:
          packages:
            - g++-7
          sources:
            - ubuntu-toolchain-r-test

    - env: COMPILER=g++-7 BUILD_TYPE=Release
      addons: *gcc7

    # GCC 8
    - env: COMPILER=g++-8 BUILD_TYPE=Debug
      addons: &gcc8
        apt:
          packages:
            - g++-8
          sources:
            - ubuntu-toolchain-r-test

    - env: COMPILER=g++-8 BUILD_TYPE=Release
      addons: *gcc8

script:
  - mkdir build && cd build
  - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_CXX_COMPILER=$COMPILER -DDEV_MODE=ON
  - cmake --build . -- VERBOSE=1